### ISSUE TITLE
mapping translocation

### ISSUE THREAD

**Issue by olechnwin** [agshumate/Liftoff#100]
Hi,

I have assembled genome that I tried to annotate by lifting the hg38 annotation over. The contig pictured below has a translocation of EWSR1 (chr22) and FLI1 (chr11) . As shown below, the FLI1 is annotated successfully and to the right of FLI1 is RHBDD3 which was right next to EWSR1. Is there any parameters I should try so I can get parts of the EWSR1 annotated in this region?
Thank you in advance for your help.

![ewsfli](https://user-images.githubusercontent.com/20069067/142483422-b857aad0-d63b-4e27-81be-56d64fdfdb8d.png)

**Comment by agshumate** [comment]
Hi,
Were parts of EWSR1 annotated anywhere else within your genome?

**Comment by olechnwin** [comment]
Hi,
Yes. It is annotated in another scaffold.

**Comment by agshumate** [comment]
In these cases, Liftoff will just map the gene once to whatever contig the majority of the sequence is located. One work around to this would be to split the EWSR1 annotation in your reference gff gene into the two fragments that map to different scaffolds.

**Comment by olechnwin** [comment]
Ahhh.....thank you so much for your suggestion.
Can you please elaborate on what you mean by splitting the EWSR1 annotation? I've never done this before.
If I have EWSR1's exons 1-5 that map to scaffold 1 and exons 6-9 that map to scaffold 2, Do I split the annotation of EWSR1 into a gene with exons 1-5 and have another annotation for EWSR1 but named it EWSR1_2? with exons 6-9? Do I need another annotation of full length EWSR1?
Thank you again.

**Comment by agshumate** [comment]
yes what you said is exactly what i had in mind. one annotation with exons 1-5 and another with 6-9. no need to add a full length annotation of EWSR1

**Comment by olechnwin** [comment]
I probably spent too much trying to find a software that can help me modify the gff3 file but still cannot find it.
Please let me know if you have any recommendation. Thanks!

**Comment by agshumate** [comment]
Hi there,
I was thinking to just manually edit the gff file. I'm not sure of any software that can do this automatically. If you comment with the gff3 annotation of EWSR1 here I can respond with the proper edits to make to your file

**Comment by olechnwin** [comment]
Thank you so much for your quick reply and kind offer.
I tried to find a software to edit the gff3 because the gff that I used contained 461 lines of EWSR1 annotation.
I'll try to get the lines and figure out where to split the exons and post back here tomorrow.

**Comment by agshumate** [comment]
you can email it to me at alainashumate@gmail.com if there are that many lines

**Comment by olechnwin** [comment]
Thank you again for your help with this. I really appreciate your time since this is completely new for me.

I've uploaded the entire gff3 file that I used to run liftoff since I thought it would be easier and my email server does not allow me to send a file this big. Link to [gff3](https://www.dropbox.com/s/8r7neyujngchx9i/gencode.v38.chr_patch_hapl_scaff.annotation.gff3?dl=0) file.

The fusion gene is EWSR1 (transcript name = EWSR1-206, exon 1 thru 7) and FLI1 (transcript name= FLI1-207, exon 6 thru 9)
I am giving you the transcript name since the gff seems to be organized by transcript. I am also expecting the reciprocal gene FLI1 and EWSR1. 

Please let me know if you have any additional questions.

Many thanks for your help.

**Comment by olechnwin** [comment]
Thank you so much for your help. I am happy to report that I was able to map the EWSR1 by splitting it.
I tried to do similar process for FLI1 but it doesn't work the way I thought it should.
For anyone trying to do similar thing, I looked for the transcript EWSR1-206 and FLI1-207 in the gff3 and copied it to the end of the file. I then modified the lines so they looked like this:
```
chr22   HAVANA  gene    29268009        29287134        .       +       .       ID=EWSR1split;gene_name=EWSR1split
chr22   HAVANA  exon    29268268        29268349        .       +       .       ID=exon1;Parent=EWSR1split
chr22   HAVANA  exon    29272216        29272252        .       +       .       ID=exon2;Parent=EWSR1split
chr22   HAVANA  exon    29272380        29272431        .       +       .       ID=exon3;Parent=EWSR1split
chr22   HAVANA  exon    29273741        29273864        .       +       .       ID=exon4;Parent=EWSR1split
chr22   HAVANA  exon    29278030        29278216        .       +       .       ID=exon5;Parent=EWSR1split
chr22   HAVANA  exon    29282390        29282557        .       +       .       ID=exon6;Parent=EWSR1split
chr22   HAVANA  exon    29286923        29287134        .       +       .       ID=exon7;Parent=EWSR1split
chr11   HAVANA  gene    128686535       128813267       .       +       .       ID=FLI1split;gene_name=FLI1split
chr11   HAVANA  exon    128805366       128805431       .       +       .       ID=exon7;Parent=FLI1split
chr11   HAVANA  exon    128807180       128807239       .       +       .       ID=exon8;Parent=FLI1split
chr11   HAVANA  exon    128809157       128809204       .       +       .       ID=exon9;Parent=FLI1split
chr11   HAVANA  exon    128810459       128813267       .       +       .       ID=exon10;Parent=FLI1split
```
Re-running liftoff with this gff3 file, EWSR1split is annotated (there is another EWSR1 in another scaffold). But, then FLI1split is annotated where FLI1 was. I blasted the region in between the annotated EWSR1split and FLI1 (~75k), it mapped to FLI1.
![ewsfli](https://user-images.githubusercontent.com/20069067/149357107-d2573769-e9f2-4c35-8850-19da4aee36a2.png)

Should I split the FLI1 further? I think this means FLI1 is duplicated. How can I annotate duplicated genes?

Thanks again for your help.

**Comment by agshumate** [comment]
Im glad you got it to work for EWSR1. If FLI1 is duplicated rather than split, you don't need to split the annotation. To annotation a duplication, use the -copies option in liftoff

**Comment by olechnwin** [comment]
Actually, based on this annotation, there is no full length FLI1. The FLI1 that was annotated, was only exons 7-10 even without splitting the annotation. I'll try to use the -copies option. Thanks!

**Comment by olechnwin** [comment]
To clarify, is there a way to annotate parts of a gene that are in multiple locations?

**Comment by olechnwin** [comment]
Sorry for the confusion. 
In the original gff3 file, FLI1 has exon 1-10. When I ran liftoff, it annotated FLI1 with less than 10 exons. This is fine as it is expected for FLI1 to not have all its exons in the assembled genome. However, since the fusion gene EWS/FLI is known to be expressed, I was expecting the FLI1 exons to be closer to EWSR1 exons. Which led to me blast the region in between FLI1split and EWSR1split and found sequences matching FLI1 in this region. I thought this mean some of FLI1 exons are duplicated in this region.
So, my question is there a way to get FLI1 (or parts of FLI1) annotated especially in the region in between EWSR1split and FLI1split region (the region with no annotation above where I show the blast hits)?
I hope this make sense. Thank you.

**Comment by agshumate** [comment]
i see. so just to confirm, you are expecting a duplication of exons 7-10 rather than a split annotation of FLI1? By split annotation i mean exons 1-6 in one location and 7-10 in another.

**Comment by olechnwin** [comment]
Sorry. There are actually two different things.
I actually are expecting a split annotation of FLI1. Exons 1-6 in one location and 7-10 in another. But liftoff only annotated exon 7-10.
At the same time, I was looking at the gap in between annotation of EWSR1 exons 1-7 and FLI1 exons 7-10 and found that the sequences in the middle matching FLI1. So, I thought FLI1 exons (I'm not sure which one) is also duplicated in this region.

**Comment by agshumate** [comment]
Okay. I'm not sure liftoff is the best tool to use in this case. Liftoff tries to find a mapping where the intron /exon structure is the same in the target genome. There may be a work around by editing the annotation but it would take a good deal of trial and error to figure it out. You may have more success using a traditional eukaryotic gene finder to annotate this region of interest. Sorry I couldnt offer more help

**Comment by olechnwin** [comment]
That's what I thought. Thank you so much for your help and insights. You've been very helpful.
Liftoff is a very good tool to do a quick annotation for genome assembly. It's fast and easy to run. So Thank you!
