### ISSUE TITLE
using liftoff with bacterial genomes?

### ISSUE THREAD

**Issue by 0xaf1f** [agshumate/Liftoff#102]
I was wondering whether there would be any issues in applying liftoff to bacterial genome annotations. I found one issue in https://github.com/agshumate/Liftoff/blob/master/liftoff/polish.py where something like `protein = longest_ORF.translate()` is run using the default translation table. I'm wondering whether it might be better to identify the translation table in the reference annotation (like from the `transl_table` qualifier) and then use that everywhere. Or making it a flag.

**Comment by agshumate** [comment]
Hi,
the -polish option does use the default translation table. . However since bacterial genome annotations are much simpler, you should be able to get very good results without needing the -polish option

**Comment by 0xaf1f** [comment]
Oh, we already had a script to find reference genes by blasting to our sample genome. We thought it'd be better to use liftoff to get extra QA steps like this--making sure beginnings and ends are start/stop codons, etc.
