### ISSUE TITLE
trouble w/ -unplaced

### ISSUE THREAD

**Issue by dirkjoldersma** [agshumate/Liftoff#103]
Hi, 

I'm struggling to take advantage of -unplaced option.

This command works perfectly:

$ liftoff -db Fvesca_h4.gff3_db -o only_chromes_option.gff3 -chroms chromosomes_list.txt YW.ragtag.polca.fasta Fvesca_h4.fasta

This command fails ... 

$ liftoff -db Fvesca_h4.gff3_db -o No_options_but_unplaced.gff3 -chroms chromosomes_list.txt -unplaced unplaced_list.txt YW.ragtag.polca.fasta Fvesca_h4.fasta

and the error is: 

lifting features
mapping unplaced genes
**GFF does not contain any gene features. Use -f to provide a list of other feature types to lift over.** (No GFF output is produced.)

I populated the unplaced_list by grep tig reference.fasta > unplaced_list.txt (see below). 

Appreciate your advice.

Thx - 
DJ

$ cat unplaced_list.txt 
>contig_1
>contig_10
>contig_11
>contig_12
>contig_13
>contig_14
>contig_15
>contig_16
>contig_17
>contig_18
>contig_19
>contig_2
>contig_20
>contig_21
>contig_22
>contig_3
>contig_4
>contig_5
>contig_6
>contig_7
>contig_8
>contig_9

$ grep tig Fvesca_h4.fasta
>contig_1
>contig_10
>contig_11
>contig_12
>contig_13
>contig_14
>contig_15
>contig_16
>contig_17
>contig_18
>contig_19
>contig_2
>contig_20
>contig_21
>contig_22
>contig_3
>contig_4
>contig_5
>contig_6
>contig_7
>contig_8
>contig_9

**Comment by agshumate** [comment]
Hi,
do you have gene features on those unplaced contigs?
