### ISSUE TITLE
How to use liftoff by inputing an existing sam file generated by minimap2?

### ISSUE THREAD

**Issue by comery** [agshumate/Liftoff#106]
Hi,

Thank you for developing this useful tool!
I see liftoff requires a target and reference genomes to do minimap alignment first, and then lift the features over from the user's input.
I am wondering is there a way to use liftoff by giving it my own alignment results? because I have done two large genome alignments which was a computational consuming process, I don't want to do it again.

Best wishes

**Comment by agshumate** [comment]
Hi,
currently there is no way to provide your own alignments. It is important to note that liftoff will align only the gene sequences to the target genome which is much faster than doing whole genome alignment of two large genomes.

**Comment by comery** [comment]
Hi,
Do you mean that when I give a gff file as input, actually, liftoff will parse gff and extract the gene regions only and then map these regions to the query genome, rather than leftover positions based on a whole-genome alignment?

**Comment by agshumate** [comment]
yes exactly

**Comment by comery** [comment]
Thank you for sharing this infomration! now I know why liftoff runs so fast!
