### ISSUE TITLE
Can we combine the annotation results to improve the integrity

### ISSUE THREAD

**Issue by ld9866** [agshumate/Liftoff#109]
Thank you very much for developing such good software!
At present, we have annotated our genome completely, but we find that our annotation is not very complete. 
Now we want to use the software you developed to map a high-quality annotation of the reference genome to our genome for annotation, and then combine the two annotation files. We want to ask whether this operation is possible?
Good luck!

**Comment by agshumate** [comment]
Hi,
This operation is not directly possible with liftoff but my recommendation would be to find genes in the liftoff results that do not overlap your current annotation using bedtools intersect -v and then add those genes to your annotation. If you have further questions about the specifics of this, please email me at alainashumate@gmail.com

**Comment by ld9866** [comment]
Very happy to receive your reply!
Recently, our server has had some problems and there is no way to try it immediately.  I will try it according to your suggestions.
thank you!
