### ISSUE TITLE
Can we convert coordinates in bed format?

### ISSUE THREAD

**Issue by guandailu** [agshumate/Liftoff#112]
Can we convert coordinates in bed format?

**Comment by amanda128891** [comment]
I actually was working with this exact file format today also! I used this tool to convert my bed file to gff: https://usegalaxy.org/root?tool_id=bed2gff1

I don't believe bed is a currently accepted format.

**Comment by agshumate** [comment]
Bed is not supported as liftoff is specifically designed for lifting over genes
