### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by aaronmck** [agshumate/Liftoff#14]
Thanks for the great tool, it will be really helpful to genome annotation efforts out there! I tested out mouse-like genome assembly against the mouse GFF3 annotations. Everything was going fine, but at some point in the 'lifting features' portion, memory usage went crazy: I'm on a 1TB shared server, and the python process was using ~400g of memory. Any thoughts on what would have caused this? I'm happy to try things out. Thanks again!

**Comment by agshumate** [comment]
Hi there! I'm hoping you can give me a little more info about your data, or if it is publicly available, links would be even better. Specifically, how many total features are in your GFF file and how many of them are genes? I'm not sure what may be causing this - when I lift over ~40,000 genes from one human assembly to another, I do not exceed ~15 Gb of memory, so i definitely would like to investigate this further. Thanks!

**Comment by aaronmck** [comment]
I'm going to try and filter down the input GFF feature set and watch memory growth a little more closely. If I can still trigger it I'll find a way to share my setup with you (this should be a low priority for you).

**Comment by aaronmck** [comment]
I filtered down the Ensembl mouse GFF3 with a simple grep 'Parent\|gene', which ran to completion with less than 100G. Not sure what was wrong with the whole GFF. The default GFF has a lot of 'biological_region' annotations, maybe that was the issue. Regardless, the problem is solved! I'll close the issue, thanks again for the great tool!

**Comment by agshumate** [comment]
I'm glad you were able to run it to completion. 100G still seems high to me so I will continue to do some investigation. I have noticed that "biological_region" and other similar features cause the program to run very slowly and perhaps this is the source of the high memory usage as well. often these "regions" are entire chromosomes that don't really need to be lifted over in this manor. I am thinking of making the default to lift-over genes features and all of their associated child features (transcripts, mRNAs, exons, CDS, etc) and making it optional to provide a list of additional feature types to lift-over

**Comment by aaronmck** [comment]
yeah, I think there's the temptation to lift over the "biological_region" annotations if you're interested in looking at synteny around genes, so I would guess other people might try. Some build-in filtering would certainly help people get it right. Thanks again!
