### ISSUE TITLE
Incorrect GFF/GTF syntax on line 5r relations: 0 features

### ISSUE THREAD

**Issue by Naveen-kumar-Pandey** [agshumate/Liftoff#142]
i am using latest version of liftoff but i am getting this type of issues 
commands:-  liftoff -g GCF_016906535.1_ASM1690653v1_genomic.gtf -o Candida_Albicans.gtf -u unmapped_feature -dir Liftoff -p 10 -infer_genes -infer_transcripts -copies assembly.fa Rhizoctonia_solani.fna
Issue :-
extracting features
/home/bioinfo/.local/lib/python3.8/site-packages/gffutils/create.py:733: UserWarning: It appears you have a gene feature in your GTF file. You may want to use the disable_infer_genes=True option to speed up database creation
  warnings.warn(
ERROR:Incorrect GFF/GTF syntax on line 5r relations: 0 features

please suggest what we do to resolve this issues

**Comment by margaretwoodhouse** [comment]
I am also having this issue since I updated to the latest version of liftoff (as of May 10 2023), with gff files I've used successfully with earlier versions of liftoff. Is the latest version less permissive of variations in gff formats--which unfortunately are ubiquitous?
