### ISSUE TITLE
Liftoff is running so slow

### ISSUE THREAD

**Issue by yeeus** [agshumate/Liftoff#163]
I had run liftoff to map annotations between 2 human genomes two weeks ago, and it's still running. 
I found that it seems liftoff is running using only one cpu (indicated by `top`). Is there any method to accelerate it?
Here is my script:
```
#!/bin/sh
#SBATCH --job-name=liftoff
#SBATCH --partition=cpu64
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=64
#SBATCH --mem=300g

liftoff ${target} ${ref} -sc 0.95 -copies -g ${gff} -polish -o MF2_mat.v0.9.liftoff.gff -f type.list -exclude_partial -p 300
```

Best wishes!

**Comment by zgb963** [comment]
Same thing happened to me when I was running it. You can accelerate it by increasing the number of cpu cores and memory (i.e. 150-250GB RAM compute node with 16-32 cores)

**Comment by yeeus** [comment]
I guess there are some steps being stuck but I don't know why.
I tried using liftoff with per chromosome and it seems faster. But this problem happend occasinally, But that's ok.

**Comment by zgb963** [comment]
> I guess there are some steps being stuck but I don't know why. I tried using liftoff with per chromosome and it seems faster. But this problem happend occasinally, But that's ok.

Hi, how were you able to run liftoff with per chromosome? Did it finish running and output a new annotation?

**Comment by yeeus** [comment]
yeah sure， just input one chromosome with corresponding chromosome of reference
