### ISSUE TITLE
Liftoff with copies leads to duplicated ID + Copy number

### ISSUE THREAD

**Issue by mtvector** [agshumate/Liftoff#17]
I'm finding that when I run Liftoff with the -copies flag, it will find copies of genes in different locations, but it won't give them a unique ID or extra_copy_number, or anything to identify them. I'm assuming this is a bug?

For instance:

```
NTIC01022223.1  Liftoff transcript      138600727       138602100       .       -       .       transcript_id "ENST00000474381.1-0"; gene_id "Rhesus_G0040478"; gene_name "HLA-B"; copy_id "ENST00000474381.1-0_30"; coverage "1.0"; sequence_ID "1.0"; extra_copy_number "6";

NTIC01022223.1  Liftoff transcript      138801942       138803360       .       -       .       transcript_id "ENST00000474381.1-0"; gene_id "Rhesus_G0040478"; gene_name "HLA-B"; copy_id "ENST00000474381.1-0_30"; coverage "1.0"; sequence_ID "1.0"; extra_copy_number "6";
```

Thanks for the hard work! Your code is awesome!

**Comment by agshumate** [comment]
hi there! thanks for pointing this out- it is indeed a bug. i just merge a couple very small changes that should fix the issue. please let me know if it doesn't
