### ISSUE TITLE
De novo annotation case

### ISSUE THREAD

**Issue by sivico26** [agshumate/Liftoff#20]
Hi there! wonderful tool! I was wondering about an alternative use for Liftoff and wanted to ask your opinion.

I am currently working on the _de novo_ genome assembly of a non-model plant. Assembly is finished (quite fragmented to be honest) so we moved to annotation. I was wondering if I could use Liftoff to help with the annotation. In my mind, I would use Liftoff to map the annotations of reference genomes of other species to the assembly of my species and maybe provide the results as evidence to more robust pipelines like Maker. 

The catch here though is that the references are that close. We are talking about species on the same family/subfamily, something I imagine not on your scope when you designed Liftoff. 

So what do you think? Do you think it is feasible this repurpose? Or on the other hand, due to the high evolutionary distances, something might go wrong and actually create more noise than a helpful signal to downstream analysis?

Your thoughts are very valuable to me. 
Thank you in advance.

**Comment by agshumate** [comment]
Hi! This is an interesting question that I do not yet have the answer too but plan to start exploring soon. The success of gene lift over depends on the minimap2 alignments and minimap2 can theoretically align sequences that diverge up to ~15%. So I imagine that liftoff will not work with any genomes where the exon sequences diverge more than this. I don't think that problematic noise would be created necessarily - if it does not work, the genes will simply fail to map. you can specify a minimum alignment coverage and sequence identity to count a gene as mapped, and anything that maps below these thresholds will be tagged as partial_mapping=True and low_identity=True in the output GFF so they can be easily filtered out downstream. 

I certainly think it is worth trying and I would be curious to hear how it works for you!

**Comment by Juke34** [comment]
minimap2 alignments are used in several pipelines as evidence aligner to feed proper annotation tool like MAKER or EVM. So using liftoff output should be fine and probably better.
