### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by evolgen** [agshumate/Liftoff#25]
Hi developers,

I am facing installation problems with liftoff, however I was able to install the older version successfully.
This is the error -
```
Traceback (most recent call last):
  File "./bin/liftoff", line 33, in <module>
    sys.exit(load_entry_point('Liftoff==1.2.2', 'console_scripts', 'liftoff')())
  File "./bin/liftoff", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
```

I tried using a local directory installation and a conda environment installation, but dont seem to work.
Could you please help me resolve it?

Thanks,
Rohit

**Comment by agshumate** [comment]
hi,
please try installing v1.2.3 rather than 1.2.2

**Comment by evolgen** [comment]
Hi Alaina,

Sorry but the same error persists for 1.2.3 too.

**Comment by agshumate** [comment]
can you check your PYTHONPATH environment variable and ensure it is the correct local directory?

**Comment by evolgen** [comment]
errrr it was the PYTHONPATH problem - I activated a conda environment and it was missing. Thanks for the help :)
