### ISSUE TITLE
How does -sc parameter impact the output

### ISSUE THREAD

**Issue by skyungyong** [agshumate/Liftoff#27]
Hello, 

Running Liftoff with -p 20 -a 0.4 -s 0.4 -sc 0.4 -copies produced 12108 genes with coverage=1.0 and 13196 total genes. On the other hand, the same process with a change in -sc from 0.4 to 1.0 generated 11880 genes with coverage=1.0 and 12544 total genes. 

The additional genes with coverage=1.0 captured with -sc 0.4 includes cases like this "coverage=1.0;sequence_ID=0.99824". I thought -sc will be used to determine whether a gene can be considered as a copy of another gene. How does this parameter impact the outputs, and why with smaller -sc parameters, additional highly similar copies can be detected?

**Comment by agshumate** [comment]
hi,
-sc is the _minimum_ sequence identity for which a gene can be considered a copy. so if -sc is 1.0, a gene with sequence_ID=0.99824 does not meet the minimum threshold and will not be reported as a gene copy. with -sc of 0.4, a gene with seqid=0.99824 is well above the 0.4 minimum threshold and thus will be output as a copy.

**Comment by skyungyong** [comment]
I see. So even with -copies, if the default -sc is used, no genes will be reported if they have sequence identity below 100%. It makes sense! Thank you for the clarification.

**Comment by agshumate** [comment]
hi,
when you use -sc 1.0 are you not getting any genes output below 1.0? or just not extra copies below 1.0?

**Comment by skyungyong** [comment]
I am getting outputs for genes with sequence identity below 100%. I think the additional genes I was asking about are annotated to be extra copies.
