### ISSUE TITLE
Missing complete target exon with high identity to reference

### ISSUE THREAD

**Issue by charlesfeigin** [agshumate/Liftoff#29]
Hi,

I've noticed that after running liftoff, a single exon from a candidate gene of interest is missing from the output liftover annotation. This exon is present in my reference species, has ~93% identity with my target species (with the few SNPs spread fairly evenly over the exon) and is fully represented in the target genome (e.g. a blast search returns a single, full-length match at the correct genomic coordinates). This exon should pass both the minimum alignment coverage (a) and minimum sequence identity for child features (s). Do you have a sense of why this exon may not have been lifted over? My concern is that if an exon is missing in my candidate others may be missing from other genes.

edit: Also, I'm using version v1.3.0

Thanks!

**Comment by agshumate** [comment]
Hi,
Is the intron in the target genome larger than the reference? If so, it may be the case that minimap2 did not align the gene end to end, but rather aligned it in two fragments. To avoid genes mapping incorrectly across large genomic distances,  by default Liftoff will only consider fragmented alignments where the distance spanned by the fragments in the target genome is no greater than 2 times the distance in the reference genome. This maximum distance threshold can be increased with the -d option. 

To get a better sense of what is going on, it can be helpful to look at the minimap2 sam output in the intermediate files output. with that you can check to see if the gene aligned end-to-end or not.

**Comment by charlesfeigin** [comment]
Embarrassed, that was it. I had done several runs changing the d parameter before and the overall output had changed relatively little (genome structure in these species is quite conserved) so I had decided to just stick with the default. My candidate is one of the small number of exceptions, the intron on one side of the 'missing' exon is 2.97X time the length in the target species as the reference species. Upping it to 4 caught that exon. Thanks so much!
