### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by WengangxJJ** [agshumate/Liftoff#33]
Hi, 
    I am trying to install Liftoff, while with the error report when I use 'pip install Liftoff' as follow. Could you kindly point me how to copy with the problem?
    Many thanks,
    Wengang
.....................
ERROR: multiqc 1.8.dev0 has requirement matplotlib<3.1.0,>=2.1.1, but you'll have matplotlib 3.1.2 which is incompatible.
Installing collected packages: numpy, biopython, pyfaidx, argh, argcomplete, gffutils, networkx, pysam, interlap, Liftoff
    Running setup.py install for numpy ... error
    ERROR: Command errored out with exit status 1:
     command: /exports/applications/apps/SL7/anaconda/5.0.1/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t6vivbcn/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-t6vivbcn/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-dvqzpuz1/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/s1874451/.local/include/python3.6m/numpy --prefix=/home/s1874451/schoenebeck_group/WENGANG/python_lib
         cwd: /tmp/pip-install-t6vivbcn/numpy/
    Complete output (34 lines):
    Running from numpy source directory.

    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install numpy`   (last NumPy release on PyPi)
..................

**Comment by agshumate** [comment]
Hi Wengang,
Which version of python are you running?

**Comment by WengangxJJ** [comment]
> Hi Wengang,
> Which version of python are you running?
  

Hi Agshumate,
I used 3.6.3 from anaconda/5.0.1
Thanks.

[s1874451@tc04(eddie) WENGANG]$  python -V
Python 3.6.3 :: Anaconda, Inc.

**Comment by agshumate** [comment]
Okay this should not be the problem then. it looks like it is failing when trying to install numpy. Are you able to successfully run "pip install numpy"? if not, it is maybe something to do with your environment rather than a specific problem with Liftoff.

**Comment by WengangxJJ** [comment]
Hi， I figure it out by creating a new conda environment. Many thanks!
