### ISSUE TITLE
Most of annotation fail to be converted by liftover can be successfully converted by liftoff

### ISSUE THREAD

**Issue by XiaoyuZhan520** [agshumate/Liftoff#38]
Dear authors,

I used liftoff to see how many annotation that liftover fail to convert can be converted. The result showed that 99% of them can be mapped to target genome by liftoff. All of them have no extra copy.

I am surprised by the huge different result produced by liftover and liftover.  Do yo have any idea of how this happen?

Sincerely yours
Christina

**Comment by agshumate** [comment]
HI there,
when you say liftover, are you referring to the UCSC liftover tool?
