### ISSUE TITLE
sequence_ID tag

### ISSUE THREAD

**Issue by mrvollger** [agshumate/Liftoff#39]
Hi, 

I am wondering how the identity reported in the sequence_ID tag is calculated. For example does a single indel event count as one difference, or is the size of the indel taken into account?

Thanks!
Mitchell

**Comment by agshumate** [comment]
hi,
the size of the indel is taken into account. the sequence_ID does not take into account mismatches or indels in introns however.

**Comment by mrvollger** [comment]
Thanks for the quick reply! 

One more question? 
If you use the -d option to extend the query sequence will that become part of the sequence identity calculation?

**Comment by agshumate** [comment]
no, the flanking sequence will be ignored for the sequence identity calculation
