### ISSUE TITLE
-f flag broken in v1.5.0?

### ISSUE THREAD

**Issue by pkerpedjiev** [agshumate/Liftoff#46]
I just upgraded to v1.5.0 but when I run the following command:

`liftoff -g hg38.refGene.short.gtf.gz -f feature_types.txt chm13.draft_v1.0.fasta.bgz hg38.fa.bgz`

I get a `GFF does not contain any gene features. Use -f to provide a list of other feature types to lift over.` error.

When I downgrade back to v1.4.2, it starts running as usual (albeit with [the running time issue](https://github.com/agshumate/Liftoff/issues/16#issuecomment-703149628)). Anything change related to that flag?

**Comment by agshumate** [comment]
Hi there, thanks for submitting this issue - it does look like the -f flag broke in 1.5.0 with gtf files only. i fixed the problem in 1.5.1 so you can upgrade to this version or use a gff3 file with 1.5.0

**Comment by pkerpedjiev-zymergen** [comment]
Thank you for the quick response! And sorry about the duplicate issue. I must have hit submit and then gone back to edit the formatting.

**Comment by pkerpedjiev** [comment]
Thank you for the quick response! And sorry about the duplicate issue. I must have hit submit and then gone back to edit the formatting and hit submit again.
