### ISSUE TITLE
minimap2 parameters

### ISSUE THREAD

**Issue by charlesfeigin** [agshumate/Liftoff#53]
Hi, I just had a quick question. In the usage message for liftoff, mismatch and gap open penalties of 2 are given for exons. Is this penalty used exclusively for exons or for all feature types (i.e. if I am lifting over a non-coding element that does not have an exon feature, is mismatch penalty of 2 used or the minimap2 default of 4)? Thanks!

**Comment by agshumate** [comment]
hi there,
to offer some clarification, liftoff first aligns the parent feature (usually genes but other features can be specified with -f) with minimap2. for this step, the default minimap2 parameters are used but this can be changed with -mm2_options. In the next step, liftoff looks at all of the minimap2 alignments for each gene or feature, and then scores them according to the number of mismatches, and gaps within the children features. This is where the -mismatch, -gap_open, and -gap_extend parameters come into play. so this is only necessary when there is more than one possible alignment for the child(ren).  For gene features, the children are exons, but these parameters will be applied to a child of any type. If the feature does not have any children (like a repeat element or something), these parameters will apply to the whole feature. I hope that helps!

**Comment by charlesfeigin** [comment]
Thank you for the clarification!
