### ISSUE TITLE
conda install retrieves earlier version of liftoff

### ISSUE THREAD

**Issue by margaretwoodhouse** [agshumate/Liftoff#66]
Hi, there:

I'm trying to install the latest release of liftoff. Based on having similar issues as https://github.com/agshumate/Liftoff/issues/48, I used the command

`conda create -n liftoff -c bioconda -c conda-forge liftoff`

to install. However, when I write` liftoff -V` to see the version, it says

`v1.4.2`

and not v1.5.X as I expect. The option for `-mm2_options` is also missing, showing this indeed is an old version of liftoff. Is using conda-forge causing an old version to be installed?

Thanks!

**Comment by agshumate** [comment]
Hi Margaret,
Have you previously installed v1.4.2? If so maybe your system is trying to run that rather than the newly installed 1.5.X.  If so, I would trying again with a new name for your conda env.  something like
`conda create -n liftoff_1.5 -c bioconda -c conda-forge liftoff`

and then being sure to activate env liftoff_1.5. if that doesnt work please let me know

**Comment by margaretwoodhouse** [comment]
Hi there:

I had removed the previous liftoff environment already; then I removed the one I installed the other day, then ran the command you posted: `conda create -n liftoff_1.5 -c bioconda -c conda-forge liftoff`, but the version is still `v1.4.2`. 

I then removed that conda enviroment and next tried `conda create -n liftoff_1.5.2 -c bioconda -c conda-forge liftoff=1.5.2` to specifically request the correct version of liftoff, but I am still getting `v1.4.2` as the version. Since I've removed all old liftoff conda environments before attempting to create new ones, I am not sure what to do next. Thanks for any help you can give.

**Comment by agshumate** [comment]
Hi,
If you execute `conda list -n liftoff_1.5` does list v1.4.2 or 1.5.2?

**Comment by margaretwoodhouse** [comment]
It is `1.5.2` when I type `conda list -n liftoff_1.5`. However, when I type `liftoff -V` I get `v1.4.2`; and when I type `liftoff -h` I get

```
usage: liftoff [-h] (-g GFF | -db DB) [-o FILE] [-u FILE] [-exclude_partial]
               [-dir DIR] [-a A] [-s S] [-n N] [-d D] [-flank F] [-V] [-p P]
               [-m PATH] [-f TYPES] [-infer_genes] [-infer_transcripts]
               [-chroms TXT] [-unplaced TXT] [-copies] [-sc SC] [-overlap O]
               target reference
```
And those commands are missing many commands that are in the readme on the liftoff github, which are

```
usage: liftoff [-h] (-g GFF | -db DB) [-o FILE] [-u FILE] [-exclude_partial]
               [-dir DIR] **[-mm2_options =STR]** [-a A] [-s S] [-d D] [-flank F]
               [-V] [-p P] [-m PATH] [-f TYPES] [-infer_genes]
               [-infer_transcripts] [-chroms TXT] [-unplaced TXT] [-copies]
               [-sc SC] [-overlap O] **[-mismatch M]** **[-gap_open GO]**
               **[-gap_extend GE]**
               target reference
```

Those commands listed in the github liftoff readme that aren't in the version I downloaded are commands I would like to use for the annotation liftovers I am doing. Thanks so much.

**Comment by agshumate** [comment]
It looks like the correct version is installed in that environment, so it seems like maybe the right environment is not activated? Did you activate it with `source activate liftoff_1.5` if so you should see something like `(liftoff_1.5) -bash-4.2$` at your command prompt,  or you can check execute `echo $CONDA_DEFAULT_ENV` which should say liftoff_1.5

**Comment by margaretwoodhouse** [comment]
Yes, I activated with `source activate liftoff_1.5` and `echo $CONDA_DEFAULT_ENV` gave me `liftoff_1.5`.

**Comment by agshumate** [comment]
i can't recreate this on my end, so i'm guessing its something specific to your conda install. It's hard for me to debug that from afar but perhaps you will have better luck install with pip or from source.

**Comment by margaretwoodhouse** [comment]
Ok, thanks for working with me on this!
