### ISSUE TITLE
Are the ORFs conserved?

### ISSUE THREAD

**Issue by Juke34** [agshumate/Liftoff#7]
It is not clear in the paper on biorxiv is the ORFs are conserved, could you tell me? I mean if the tool check when lifting protein coding genes that the lifted CDS still shape an ORF still intact.

**Comment by agshumate** [comment]
Hi, liftoff does not check this , but you can use gffread (https://github.com/gpertea/gffread)  with the -P option on the output file to identify CDS's that are truncated or have an inframe stop codon

**Comment by Juke34** [comment]
I was wondering if the tool could be classified as gene predictor based on transcript Projection like Projector, AIR, transMap or CESAR. So now I know. 
Thank you for your answer.

For me the use of the term of 'annotation' is often misleading in publications. It can be used in different ways. As genome annotation expert for me Annotation underlies the **creation of gene models** by identifying the gene structure. In your case the gene models might be broken during the liftover. So it is why I needed to clarify this point. This is something that would be nice to clarify early in your paper.

Best regards
