### ISSUE TITLE
The generated GFF file has no valid format

### ISSUE THREAD

**Issue by arturomarin** [agshumate/Liftoff#70]
Hi, 

I am trying to use this software, v1.6.1. Apparently it works fine, but the generated GFF file has not the valid format because don't have in the first line:

`##gff-version 3`

The .gff file begins with the data, it seems the header is missing.  I used the following page to verify the file
http://genometools.org/cgi-bin/gff3validator.cgi

Thanks,

**Comment by agshumate** [comment]
you can simply add the header to the liftoff output and it should work fine with downstream analysis tools which require the header to be there.
