### ISSUE TITLE
example feature types file

### ISSUE THREAD

**Issue by cmatKhan** [agshumate/Liftoff#72]
It would be nice to see an example of the feature types file, and possibly some code around checking to ensure that the additional feature is unique.

**Comment by agshumate** [comment]
sure i will add an example to the README. but i'm not sure why you want code to ensure the feature is unique? there are many features of the same type within an annotation.

**Comment by cmatKhan** [comment]
Re: the example -- that is helpful, thank you!

And agreed and understood re: the properly formatted gff/gtf input. In my own use, I was trying two different annotation files with different top level feature IDs. But, I should have figured that out before I started trying to put it into liftOff, agreed.

Thanks again -- the package both works well and is easy to use.
