### ISSUE TITLE
Cryptic errors

### ISSUE THREAD

**Issue by TonyKess** [agshumate/Liftoff#76]
Hello,
I'm getting these errors while running a liftover of a gff between different assemblies of the same species:
`ERROR: failed to open file '5': No such file or directory
ERROR: failed to map the query file `

Then get the following message:
`lifting features`

And end up with a lifted gff file that looks largely complete. Anyone have insight into this error?

Command: 
`liftoff Brian_pilon_CHR.fasta GCF_000233375.1_ICSASG_v2_genomic.fna -g GCF_000233375.1_ICSASG_v2_genomic.gff -m ~/Desktop/Software/minimap2/minimap2 -o Brian_ICSASG_v2.gff -mm2_options="-t 17"`

**Comment by agshumate** [comment]
hi,
this is a bug related to parsing the -mm2_options. it shouldn't have any effect on the output though. in your case since the only option you are changing is the number of threads, you can just run liftoff with -p 17 and minimap2 will be run with 17 threads.

**Comment by TonyKess** [comment]
Great, thanks! I'll modify the command and close this for now.
