### ISSUE TITLE
How to merge the liftoff result with the EVM results?

### ISSUE THREAD

**Issue by Huangyizhong** [agshumate/Liftoff#77]
Hi, there
 As I have used the liftoff to do the convertion of the genes form the closed species to my new genome. And I also used the normal gene annotation protocal to do the annotation of the genome, including the EVM to merge all the clues from the protein and transcripts. I want to merge the liftoff.gff3 file and the EVM.gff3 to obtain the comprehensive database for the annotation. Is there some sofrwares or scripts to do it ? 
Thanks so much!
Yizhong Huang

**Comment by agshumate** [comment]
hi,
i recommend trying stringtie --merge (http://ccb.jhu.edu/software/stringtie/index.shtml?t=manual)
