### ISSUE TITLE
How to set the chroms.txt within the two genome with unplaced contig?

### ISSUE THREAD

**Issue by Huangyizhong** [agshumate/Liftoff#85]
Hi, there
    I have a new genome with chromosomes and lots of contigs, while the ref genome also has chromosomes and contigs . I wonder how to set the chroms.txt to continue the liftoff process properly? Would you please giving me some advices? 
Thanks so much!
Yizhong Huang 
Sincerely!

**Comment by agshumate** [comment]
Hi,
sorry for my slow response. my advice is to include just the chromosome names in chroms.txt and then used the -unplaced option to provide a text file with the names of your unplaced contigs in the reference genome. This will mean that the chromosome genes will be mapped first to their corresponding chromosomes in your new genomes, and then the contigs genes will be mapped

**Comment by Huangyizhong** [comment]
> Hi,
> sorry for my slow response. my advice is to include just the chromosome names in chroms.txt and then used the -unplaced option to provide a text file with the names of your unplaced contigs in the reference genome. This will mean that the chromosome genes will be mapped first to their corresponding chromosomes in your new genomes, and then the contigs genes will be mapped

Hi,  thanks so much for your reply! There are also some contigs in my new genome! Can I set the chroms.txt and the unplaced contigs follow your. advices? 
Thanks again!
Yizhong Huang

**Comment by agshumate** [comment]
yes just put the names of the unplaced contigs in the reference genome in the unplaced file and liftoff will find the best corresponding contig or chromosome to map it to
