### ISSUE TITLE
KeyError: 'scaffoldxxx' not in 'fasta'

### ISSUE THREAD

**Issue by joncahn** [agshumate/Liftoff#89]
Hi,

I'm not sure if I'm doing something wrong, but there is a recurrent error coming up when trying to align features from unplaced contigs. It gives the error 'scaffoldxxx' not in the fasta file that it is supposed to align to. It obviously is not since the unplaced scaffolds from the two species don't have the same names.
I've seen this closed issue https://github.com/agshumate/Liftoff/issues/85 and I have followed the advice of using -chroms with a file of corresponding chromosomes chr1,chr1 chr2,chr2 etc.. and gave the unplaced contigs from the reference genome with the -unplaced option, but it seems to still look for the same name in the new/destination fasta to lift to.
Is there any way to get around this?
Thank you!

**Comment by agshumate** [comment]
hi can you please place the exact error?

**Comment by joncahn** [comment]
Sure, I just replaced the actual paths in place (by "/$path/"). I can provide some the files I used to you if necessary.
All looks good until:
aligning features
lifting features
mapping unplaced genes
Traceback (most recent call last):
  File "/$path/miniconda3/envs/default/lib/python3.8/site-packages/pyfaidx/__init__.py", line 1027, in __getitem__
    return self.records[rname]
KeyError: 'scaffold15'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/$path/miniconda3/envs/default/bin/liftoff", line 10, in <module>
    sys.exit(main())
  File "/$path/miniconda3/envs/default/lib/python3.8/site-packages/liftoff/run_liftoff.py", line 10, in main
    run_all_liftoff_steps(args)
  File "/$path/miniconda3/envs/default/lib/python3.8/site-packages/liftoff/run_liftoff.py", line 29, in run_all_liftoff_steps
    map_features_from_unplaced_seq(unmapped_features, lifted_feature_list, feature_db, feature_hierarchy,
  File "/$path/miniconda3/envs/default/lib/python3.8/site-packages/liftoff/run_liftoff.py", line 213, in map_features_from_unplaced_seq
    liftover_types.map_unplaced_genes(unmapped_features, ref_chroms, target_chroms,
  File "/$path/miniconda3/envs/default/lib/python3.8/site-packages/liftoff/liftover_types.py", line 67, in map_unplaced_genes
    extract_features.get_gene_sequences(unplaced_dict, ref_chroms, args, liftover_type)
  File "/$path/miniconda3/envs/default/lib/python3.8/site-packages/liftoff/extract_features.py", line 163, in get_gene_sequences
    write_gene_sequences_to_file(chrom, args.reference, fai, sorted_parents, fasta_out, args)
  File "/$path/miniconda3/envs/default/lib/python3.8/site-packages/liftoff/extract_features.py", line 188, in write_gene_sequences_to_file
    chrom_seq = reference_fasta_idx[current_chrom][:].seq
  File "/$path/miniconda3/envs/default/lib/python3.8/site-packages/pyfaidx/__init__.py", line 1029, in __getitem__
    raise KeyError("{0} not in {1}.".format(rname, self.filename))
KeyError: 'scaffold15 not in fasta/teosinte.fasta.'

**Comment by agshumate** [comment]
if you could provide me the reference fasta file that would be great

**Comment by joncahn** [comment]
You can find it here
https://download.maizegdb.org/Zm-W22-REFERENCE-NRGENE-2.0/
The fasta file I used is "Zm-W22-REFERENCE-NRGENE-2.0.chr_scaffolds.fa.gz"
The gff3 file is "Zm-W22-REFERENCE-NRGENE-2.0_Zm00004b.1.chr_scaffolds.gff3.gz"
While looking deeper at the files, I noticed that some scaffolds (including scaffold15 that throws the error) don't have any annotated genes. Is that the source of my issue? Should I filter the fasta file for contigs with annotated genes first then?

**Comment by agshumate** [comment]
Hi,
you should not need to filter the fasta. Can you check to see if the fasta index (.fai) contains scaffold15 in it? If it doesnt, likely something went wrong in the initial build of the index and liftoff does not build a new index if it sees a .fai present. If this is the case you can fix it by deleting the .fai file and re-running liftoff. If this is not the case please let me know and I will look into it further.

**Comment by joncahn** [comment]
Hi,
I checked and "scaffold15" is in the index file.
`cat Zm-W22-REFERENCE-NRGENE-2.0.chr_scaffolds.fa.fai
chr1    310925244       6       80      81
chr2    244237062       314811822       80      81
chr3    241278614       562101854       80      81
chr4    254269898       806396457       80      81
chr5    222590201       1063844735      80      81
chr6    171602414       1289217320      80      81
chr7    181422836       1462964771      80      81
chr8    182570339       1646655399      80      81
chr9    163066665       1831507874      80      81
chr10   149450367       1996612880      80      81
scaffold15      2424934 2147931389      80      81
scaffold107     1210336 2150386648      80      81
scaffold265     576778  2151612127      80      81
scaffold21      483059  2152196127      80      81
....`
I tried to only include the unplaced scaffolds that contain annotated genes in the -unplaced file, and got the same error on scaffold107, even though it is also present in the fai index file, as you can see above.
Thank you in advance for your help.

**Comment by agshumate** [comment]
can you please post the exact command you are running?

**Comment by joncahn** [comment]
liftoff -g ${gff} -o results/W22_on_TIL11_v1.gff3 -u results/W22_on_TIL11_v1_unmapped.txt -dir ${TMPDIR} -p ${threads} -polish -chroms chroms_w22_til11.txt -unplaced unplaced_w22.txt ${w22fasta} ${tilfasta}

**Comment by agshumate** [comment]
I'm im understanding correctly,  ${w22fasta}  is your reference and ${tilfasta} is your target? if this is the case, you need to switch the order of these two parameters. The first positional arg should be your target genome and the second, your reference

**Comment by joncahn** [comment]
Of course, so sorry to have wasted your time.
