### ISSUE TITLE
Question on UnboundLocalError: local variable 'feature_db' referenced before assignment

### ISSUE THREAD

**Issue by hengjwj** [agshumate/Liftoff#90]
Hi Alaina, 

Thanks for creating this tool. I also encountered the same error as others:

> _UnboundLocalError: local variable 'feature_db' referenced before assignment_

I think my problem mainly arose from this function and the write permissions of my folder:

> **def build_database(db, gff_file, disable_transcripts, disable_genes,):
>     if db is None:
>         try:
>             feature_db = gffutils.create_db(gff_file, gff_file + "_db", merge_strategy="create_unique", force=True,
>                                             disable_infer_transcripts=disable_transcripts,
>                                             disable_infer_genes=disable_genes, verbose=True)
>         except:
>             find_problem_line(gff_file)
>     else:
>         feature_db = gffutils.FeatureDB(db)
>     return feature_db**

A workaround I did was to run gffutils in a standalone python script like so: 

> **import gffutils
> feature_db = gffutils.create_db("my.gtf", "my.gtf_db", merge_strategy="create_unique", force=True,
>                                             disable_infer_transcripts=True,
>                                             disable_infer_genes=False, verbose=True)**

My question is - can I then use this generated database in the main liftoff call like below?

> **liftoff -db my.gtf_db \
> -o out_dir \
> -dir temp_dir \
> -infer_genes \
> -p 24 \
> target.fa \
> reference.fa**

Thank you for your attention!

**Comment by agshumate** [comment]
yes you can use that database
