### ISSUE TITLE
Able to restrict to main chromosomes only?

### ISSUE THREAD

**Issue by hengjwj** [agshumate/Liftoff#91]
Hi Alaina, is it possible to restrict liftoff to specific chromosomes within the reference fasta? I wish to ignore the chrUn_* scaffolds in my reference due to storage limitations. Thank you!

**Comment by agshumate** [comment]
Hi,
There is no way within liftoff to ignore chrUn*, so my recommendation is to make a fasta file with only the main chromosomes and to use that as your reference
