### ISSUE TITLE
pip3 install Liftoff fails

### ISSUE THREAD

**Issue by shbrainard** [agshumate/Liftoff#95]
pip3 install Liftoff fails with the following message:
ERROR: Failed building wheel for pysam
  Running setup.py clean for pysam
Failed to build numpy pysam
ERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly

However:
(liftoff) ➜  Liftoff git:(master) ✗ pip3 install numpy
Requirement already satisfied: numpy in /Users/boat/.pyenv/versions/3.10.0b2/envs/liftoff/lib/python3.10/site-packages (1.21.2)
(liftoff) ➜  Liftoff git:(master) ✗ pip3 install pysam
Requirement already satisfied: pysam in /Users/boat/.pyenv/versions/3.10.0b2/envs/liftoff/lib/python3.10/site-packages (0.17.0)

Any suggestions for how to build from source?

**Comment by agshumate** [comment]
the README provides instructions on installing from source. let me know if you have problems
