### ISSUE TITLE
could we generate peptide fasta file from liftoff?

### ISSUE THREAD

**Issue by zmz1988** [agshumate/Liftoff#97]
Hi, thanks for the great tool! I had successfully used it to lift the annotation from previously published genome to my newly assembled genome. Now I would need a peptide fasta file to do a synteny test. Do you know whether liftoff have a fast trick for this? If not, do you mind to recommend me a tool to do this? Thanks in advance!

**Comment by agshumate** [comment]
liftoff does not have a tool for this but you can use gffread with the -y option to exact the protein sequences. find gffread here https://github.com/gpertea/gffread

**Comment by zmz1988** [comment]
Thanks a lot!
